---
  app :
     name: My App
     description: Welcome to ${app.name} from config server
  my :
    list :
        values: One, Tow, Three,Four, Five and six
    greeting: Hello from Mohamad

  db :
    connection: "connection string here from config server"
    host: 127.0.0.1
    port: 1234

  management:
    endpoints:
      web:
       exposure:
        include: "*"

  spring:
   profiles:
     active: test
